<a href="https://colab.research.google.com/github/DipankarJDutta/DipankarJDutta-Biomarker-discovery-from-B-T-cells-in-FASD-GDM-with-LSTM/blob/Weights-%26-Biases/LSTM_B_T_Median_optimized%20model_keras%20weights%20and%20biases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Loading essentials
from numpy import loadtxt
from numpy import reshape
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [0]:
# Fixing random seed to 007 for reproducibility
from numpy.random import seed
seed(7)
from tensorflow import set_random_seed
set_random_seed(7)

In [0]:
# Load data
dataset = loadtxt('B-T-median.csv', delimiter = ',')


In [0]:
# Reshape 2D dataset into a 3D dataset with columns as features with one time-step
x = dataset.reshape(56, 1, 30)

In [0]:
#Specify binary output of good (1) and bad (0) learners, y, in x & print y. Learner type differentiated by population median.
y = x [:, :, -1]

In [0]:
# Define LSTM One-to-One Model with 3 LSTM cells (determined via hyperparameter optimization). Sigmoid activation on the output layer for binary classification.
model = Sequential()
model.add(LSTM(3, input_shape=(1,30)))
model.add(Dense(1, activation='sigmoid'))

In [0]:
#Compile the model 
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
#Fit the model with a 80-20 split of dataset & shuffling sample order within an epoch. Batch size updated to 8 to be an even factor of sample size of 56.
model.fit(x, y, validation_split = 0.2, batch_size = 8, epochs = 1000, shuffle = True)

Train on 44 samples, validate on 12 samples
Epoch 1/1000
44/44 [==============================] - 1s 19ms/step - loss: 0.7078 - acc: 0.4545 - val_loss: 0.7239 - val_acc: 0.4167
Epoch 2/1000
44/44 [==============================] - 0s 526us/step - loss: 0.7051 - acc: 0.4545 - val_loss: 0.7204 - val_acc: 0.4167
Epoch 3/1000
44/44 [==============================] - 0s 535us/step - loss: 0.7028 - acc: 0.4545 - val_loss: 0.7170 - val_acc: 0.4167
Epoch 4/1000
44/44 [==============================] - 0s 452us/step - loss: 0.7008 - acc: 0.4545 - val_loss: 0.7142 - val_acc: 0.4167
Epoch 5/1000
44/44 [==============================] - 0s 460us/step - loss: 0.6990 - acc: 0.4545 - val_loss: 0.7113 - val_acc: 0.4167
Epoch 6/1000
44/44 [==============================] - 0s 498us/step - loss: 0.6977 - acc: 0.4545 - val_loss: 0.7084 - val_acc: 0.4167
Epoch 7/1000
44/44 [==============================] - 0s 493us/step - loss: 0.6963 - acc: 0.4545 - val_loss: 0.7056 - val_acc: 0.4167
Epoch 8/1000
44/44 

In [21]:
# Determine Weights & Biases
print(model.layers[0].trainable_weights)
units = int(int(model.layers[0].trainable_weights[0].shape[1])/4)
print("No units: ", units)
W = model.layers[0].get_weights()[0]
U = model.layers[0].get_weights()[1]
b = model.layers[0].get_weights()[2]

W_i = W[:, :units]
W_f = W[:, units: units * 2]
W_c = W[:, units * 2: units * 3]
W_o = W[:, units * 3:]

print('W_i:')
print (W_i)
print('W_f:')
print (W_f)
print('W_c:')
print (W_c)
print('W_o:')
print (W_o)

U_i = U[:, :units]
U_f = U[:, units: units * 2]
U_c = U[:, units * 2: units * 3]
U_o = U[:, units * 3:]

print('U_i:')
print (U_i)
print('U_f:')
print (U_f)
print('U_c:')
print (U_c)
print('U_o:')
print (U_o)

b_i = b[:units]
b_f = b[units: units * 2]
b_c = b[units * 2: units * 3]
b_o = b[units * 3:]

print('b_i:')
print (b_i)
print('b_f:')
print (b_f)
print('b_c:')
print (b_c)
print('b_o:')
print (b_o)



[<tf.Variable 'lstm_2/kernel:0' shape=(30, 12) dtype=float32_ref>, <tf.Variable 'lstm_2/recurrent_kernel:0' shape=(3, 12) dtype=float32_ref>, <tf.Variable 'lstm_2/bias:0' shape=(12,) dtype=float32_ref>]
No units:  3
W_i:
[[-1.83850899e-01  4.67801273e-01 -2.83632815e-01]
 [ 1.46930337e-01  2.90878981e-01  2.46390432e-01]
 [-1.55941352e-01  4.37578231e-01  4.31475043e-02]
 [-1.35502517e-01  6.15325868e-01 -2.84724742e-01]
 [ 5.24934493e-02 -2.13224500e-01  3.26214284e-01]
 [-1.98658317e-01  4.03317690e-01 -3.55481170e-02]
 [ 7.20243931e-01 -8.99691880e-02  5.20825505e-01]
 [-2.08801255e-01 -1.50283605e-01 -7.09768832e-02]
 [ 3.03257197e-01  4.14630651e-01  8.74567926e-02]
 [-2.18445659e-01  4.40816395e-02 -1.64307624e-01]
 [-1.72547370e-01  9.89493355e-02 -8.72482061e-02]
 [-4.44452226e-01 -9.51498151e-02 -5.39118871e-02]
 [ 1.64674550e-01 -6.48289267e-03 -6.30650595e-02]
 [ 1.11273855e-01  4.34777915e-01  8.48842710e-02]
 [ 8.67106095e-02  1.57987978e-02 -2.80906796e-01]
 [ 7.35414445e